Exclude only unnecessary files from being staged
Icinga/icinga-php-thirdparty pull request #12
Opened 2023-06-26 10:34 UTC by raviks789

Currently all files except files with `.php` extension are excluded from being staged in `make-release.sh`. This has been changed to stage all files except unnecessary files.

2023-06-26 13:41 UTC, nilmerg requested changes

2023-06-26 13:41 UTC, nilmerg commented on bin/make-release.sh
> + | grep -v '/.git*' \
There may be other hidden files (like `.travis.yml` and `.php_cs`) which should not be staged. Just use `/.*` please.

2023-06-26 13:41 UTC, nilmerg commented on bin/make-release.sh
> + | grep -v '/.git*' \
There's also sometimes a `phpunit*` file. Please don't stage them as well.

2023-06-29 09:35 UTC, lippserd reviewed
Which files exactly were missing until now?

2023-06-29 10:51 UTC, raviks789 commented
> Currently all files except files with `.php` extension are excluded from being staged in `make-release.sh`. This has been changed to stage all files except unnecessary files.

files other than `.php` extension like `schema.ser` in `HtmlPurifier`, which was causing the error `file_get_contents(HTMLPurifier/ConfigSchema/schema.ser): Failed to open stream: No such file or directory`.

2023-07-12 09:13 UTC, lippserd commented on bin/make-release.sh
> + | grep -v '/\.[a-zA-Z0-9_]*'
How is this working?

2023-07-12 09:51 UTC, lippserd requested changes
I compared the file sizes for the filtered and unfiltered list of vendor files. Here is the result:

**Filtered:**
```
find vendor/ -type f \
 | grep -v '/docs/' \
 | grep -v '/doc/' \
 | grep -v '/\.[a-zA-Z0-9_]*' \
 | grep -v 'phpunit*' \
 | grep -v '/examples/' \
 | grep -v '/example/' \
 | grep -v '/tests/' \
 | grep -v '/test/' \
 | xargs du -ch | grep total
 74M	total
876K	total
```

**Unfiltered**
```
find vendor/ -type f | xargs du -ch | grep total
 66M	total
9.0M	total
```

**Note** that `xargs` processes the command in reasonable batches. Therefore, there may be multiple lines that need to be totaled.

Both yield **75M**.

I think it is perfectly fine to just add the entire `vendor` directory. Please create a new PR and let it close this one.

2023-07-17 08:20 UTC, closed without merging